### PR TITLE
added info about AL2 compile

### PR DESCRIPTION
**Pull request by lucamosca1**
Added info about clamav compile on AL2

It's my very first commit on github, for sure I'm doing something wrong :D

### CODE REVIEW

**Comment by micahsnyder** [comment]
Hi @lucamosca1 
I somehow didn't see in my notifications. Looks like a nice resource. 

Can I trouble you to also add a reference to this in the[ community resources](https://github.com/Cisco-Talos/clamav-documentation/blob/main/src/community_resources/CommunityResources.md?plain=1?) page?

**Comment by micahsnyder** [comment]
@lucamosca1  friendly ping

**Comment by lucamosca1** [comment]
Sure! I'll try to add it

**Comment by micahsnyder** [comment]
Sorry about the delay. I wasn't familiar with editing to insert a link, and was procrastinating asking you to do it.  I figured it out, and added a commit to the PR.

**Pull request merged**
